In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Student_Performance.csv")

In [3]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [4]:
df.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [5]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [6]:
df["Performance Index"] = df["Performance Index"].astype(int)

In [8]:
df["Performance Index"].dtype

dtype('int64')

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
import numpy as np

In [9]:
x = df.drop("Performance Index",axis=1)
y = df["Performance Index"]

In [13]:
x = pd.get_dummies(
    x ,
    columns=["Extracurricular Activities"],
    drop_first=True
)

In [14]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size = 0.2
)

In [15]:
model = LinearRegression()
model

LinearRegression()

In [16]:
model.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pred = model.predict(x_test)

In [18]:
y_pred

array([71.37929978, 34.59284814, 43.30394065, ..., 59.53302425,
       63.2591843 , 48.8514306 ], shape=(2000,))

In [19]:
comparison = pd.DataFrame({
    "Actual Performance Index" : y_test,
    "Predicted Performance Index" : y_pred
})
comparison

      Actual Performance Index  Predicted Performance Index
8091                        72                    71.379300
969                         34                    34.592848
3689                        42                    43.303941
3950                        56                    58.122851
2397                        46                    46.669929
...                        ...                          ...
7415                        70                    73.203855
4738                        76                    75.109708
7140                        56                    59.533024
1849                        66                    63.259184
5577                        47                    48.851431

[2000 rows x 2 columns]

In [20]:
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test,y_pred)
R2_score = r2_score(y_test,y_pred)

print("MSE:", MSE)
print("MAE:", MAE)
print("RMSE:",RMSE)
print("R^2 Score :",R2_score)

MSE: 4.1024300101357785
MAE: 1.6140791618758576
RMSE: 2.025445632480857
R^2 Score : 0.9886996850155664